# Generated by Django 4.0.3 on 2022-04-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meeting', models.DateTimeField(auto_created=True)),
                ('person', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=25)),
                ('comment', models.TextField(max_length=1000)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
