# Generated by Django 4.0.3 on 2022-05-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_tomeet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.IntegerField(verbose_name=int),
        ),
    ]
